server:
  port: 8083
spring:
  application:
    name: persistence
#Eureka实例名，集群中根据这里相互识别
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
      
      
      
      