server:
  port: 8080
spring:
  application:
    name: eureka
#Eureka实例名，集群中根据这里相互识别
eureka:
  instance:
    hostname: eureka
  client:
#    service-url:
#      defaultZone: http://localhost:8080/zuul-server/
#是否开启注册服务，因为这里如果为true表示自己注册自己，而自己就是一个服务注册方，没必要自己注册自己
    register-with-eureka: false
#是否拉取服务列表，这里我只提供服务给别的服务。
    fetch-registry: false
#    service-url:
#      defaultZone: http://localhost:8180/eureka/